import type { Metadata } from "next";

import { CodeBlock, DocsCallout, DocsNext, DocsShell } from "@/components/docs-shell";
import { createPageMetadata } from "@/lib/site";

export const metadata: Metadata = createPageMetadata({
  title: "WorkClient API reference",
  description: "Reference for WorkClient TypeScript methods, inputs, outputs, provider capabilities, prepared changes, and idempotency stores.",
  path: "/docs/reference/client",
  keywords: ["WorkClient API", "Work SDK TypeScript reference", "prepared work changes"],
});

const createClient = `function createWorkClient(options: {
  adapter: WorkAdapter;
  idempotencyStore?: IdempotencyStore;
  now?: () => Date;
}): WorkClient;`;

export default function ClientReferencePage() {
  return <DocsShell breadcrumb="Reference / Client" title="Client API reference" description="The complete normalized client surface. Provider adapters implement transport and mapping; WorkClient adds validation, plans, revisions, warning acknowledgement, and idempotency." toc={[{ id: "create", label: "createWorkClient" }, { id: "reads", label: "Read methods" }, { id: "prepare", label: "Prepare methods" }, { id: "commit", label: "commit" }, { id: "types", label: "Core types" }, { id: "capabilities", label: "Capabilities" }, { id: "store", label: "Idempotency store" }]}>
    <section id="create"><h2><code>createWorkClient</code></h2><CodeBlock code={createClient} /><p><code>adapter</code> is required. The default idempotency store is process-local memory. <code>now</code> exists for deterministic testing and should normally be omitted.</p></section>
    <section id="reads"><h2>Read methods</h2><h3><code>get(id, options?)</code></h3><CodeBlock code={`get(id: string, options?: { signal?: AbortSignal }): Promise<WorkItem>`} /><p>Returns one normalized item or throws <code>WorkNotFoundError</code>. IDs are adapter-native: a GitHub issue number, Linear ID or identifier, Jira key, or Azure work-item ID.</p><h3><code>list(input?, options?)</code></h3><CodeBlock code={`list(input?: {\n  project?: string; assignee?: string;\n  state?: WorkItemState | WorkItemState[];\n  labels?: string[]; query?: string;\n  limit?: number; cursor?: string;\n}, options?: { signal?: AbortSignal }): Promise<WorkPage<WorkItem>>`} /><p>Returns an opaque provider cursor. Never construct or parse cursors; pass <code>nextCursor</code> back unchanged.</p></section>
    <section id="prepare"><h2>Prepare methods</h2><div className="docs-signatures"><code>prepareCreate(input)</code><span>Plan a new item without writing it.</span><code>prepareUpdate(id, input, options?)</code><span>Read current state and calculate a changed-field diff.</span><code>prepareComment(id, input, options?)</code><span>Read the target and plan a comment.</span></div><p>Create plans do not have an expected revision. Update and comment plans capture the current item and opaque revision.</p></section>
    <section id="commit"><h2><code>commit(change, options?)</code></h2><CodeBlock code={`commit(change: PreparedWorkChange, options?: {\n  idempotencyKey?: string;\n  acceptWarnings?: boolean;\n  signal?: AbortSignal;\n}): Promise<CommitResult>`} /><p>Commit validates provider identity, fingerprint integrity, warning acknowledgement, idempotency state, and revision before calling the adapter.</p><DocsCallout tone="warning"><p>If a mutation starts and the provider outcome becomes uncertain, Work SDK stores an ambiguous state and throws <code>WorkAmbiguousCommitError</code>. Reconcile the provider result before another write; never blind-retry that key.</p></DocsCallout></section>
    <section id="types"><h2>Core types</h2><div className="docs-table-wrap"><table><thead><tr><th>Type</th><th>Purpose</th></tr></thead><tbody><tr><td><code>WorkItem</code></td><td>Normalized item plus provider state name, opaque revision, URL, and optional raw payload.</td></tr><tr><td><code>WorkComment</code></td><td>Normalized body, author, timestamps, and raw payload.</td></tr><tr><td><code>PreparedWorkChange</code></td><td>Serializable, fingerprinted plan for one create, update, or comment.</td></tr><tr><td><code>CommitResult</code></td><td>Receipt containing the resulting item, optional comment, replay flag, and commit time.</td></tr><tr><td><code>WorkPage&lt;T&gt;</code></td><td>Items plus an optional opaque next cursor.</td></tr><tr><td><code>WorkWarning</code></td><td>Structured provider limitation or lossy/ambiguous mapping notice.</td></tr></tbody></table></div></section>
    <section id="capabilities"><h2>Capabilities</h2><p><code>work.capabilities</code> is an immutable snapshot. Inspect it when building tools or UIs so unsupported actions are absent rather than offered and rejected later.</p><CodeBlock code={`if (work.capabilities.parentLinks) {\n  tools.push(updateParentTool(work));\n}\n\nif (!work.capabilities.multipleAssignees) {\n  schema.assigneeIds = z.array(z.string()).max(1);\n}\n\nswitch (work.capabilities.concurrency.update) {\n  case "atomic":     // provider rejects races in the write itself\n  case "preflight":  // SDK re-reads, but a small race window remains\n  case "none":\n}`} /><p><code>optimisticConcurrency</code> remains as a deprecated compatibility Boolean. New code should use the action-specific <code>concurrency</code> object.</p></section>
    <section id="store"><h2><code>IdempotencyStore</code></h2><CodeBlock code={`interface IdempotencyStore {\n  acquire(key: string, intentFingerprint: string): MaybePromise<\n    | { status: "acquired"; leaseId: string }\n    | { status: "completed"; result: CommitResult }\n    | { status: "in-flight" | "ambiguous" | "conflict" }\n  >;\n  complete(key: string, leaseId: string, result: CommitResult): MaybePromise<void>;\n  abandon(key: string, leaseId: string, outcome: "retryable" | "ambiguous"): MaybePromise<void>;\n}`} /><p>The client prefixes keys with the provider. <code>acquire</code> must be atomic across every worker using the store; use a transaction, compare-and-swap, unique insert, or conditional put. A durable <code>get</code> followed by <code>set</code> is not sufficient.</p><div className="docs-rule"><strong>completed</strong><span>Replay the stored receipt without a provider call.</span></div><div className="docs-rule"><strong>in-flight</strong><span>Throw <code>WorkInFlightError</code>; another worker owns the claim.</span></div><div className="docs-rule"><strong>ambiguous</strong><span>Throw <code>WorkAmbiguousCommitError</code>; reconcile before retrying.</span></div></section>
    <DocsNext href="/docs/reference/errors" label="Errors" description="Handle authentication, rate limits, conflicts, validation, and provider failures." />
  </DocsShell>;
}
